// --------------------------------------------------------------
// -                     Renewal Job Scripts                    -
// --------------------------------------------------------------

// ------------------------- Job Quests -------------------------
// - 1-1
npc: npc\re\jobs\1-1\acolyte_fr.txt

npc: npc\re\jobs\1-1\archer_fr.txt

npc: npc\re\jobs\1-1\mage_fr.txt

npc: npc\re\jobs\1-1\merchant_fr.txt

npc: npc\re\jobs\1-1\swordman_fr.txt

npc: npc\re\jobs\1-1\thief_fr.txt

// - 1-1 Expanded
npc: npc\re\jobs\1-1e\taekwon_fr.txt

// - 2-2
npc: npc\re\jobs\2-2\crusader_fr.txt

// - 2e
npc: npc\re\jobs\2e\kagerou_oboro_fr.txt

npc: npc\re\jobs\2e\rebellion_fr.txt

// - 3-1
npc: npc\re\jobs\3-1\archbishop_fr.txt

npc: npc\re\jobs\3-1\mechanic_fr.txt

npc: npc\re\jobs\3-1\ranger_fr.txt

npc: npc\re\jobs\3-1\rune_knight_fr.txt

npc: npc\re\jobs\3-1\warlock_fr.txt

npc: npc\re\jobs\3-1\guillotine_cross_fr.txt

// - 3-2
npc: npc\re\jobs\3-2\genetic_fr.txt

npc: npc\re\jobs\3-2\minstrel_fr.txt

npc: npc\re\jobs\3-2\royal_guard_fr.txt

npc: npc\re\jobs\3-2\shadow_chaser_fr.txt

npc: npc\re\jobs\3-2\sorcerer_fr.txt

npc: npc\re\jobs\3-2\sura_fr.txt

npc: npc\re\jobs\3-2\wanderer_fr.txt

// - Novice
npc: npc\re\jobs\novice\academy_fr.txt

// npc: npc/re/jobs/novice/novice.txt
npc: npc\re\jobs\novice\supernovice_ex_fr.txt

// - Job Repairs
npc: npc\re\jobs\repair_fr.txt

// - Doram
npc: npc\re\jobs\doram\spirit_handler_fr.txt


// ------------------------ Skill Quests ------------------------
npc: npc\re\quests\skills\merchant_skills_fr.txt

npc: npc\re\quests\skills\swordman_skills_fr.txt

