// --------------------------------------------------------------
// -                     Renewal Guild Wars                     -
// --------------------------------------------------------------

// ----------------------- War of Emperium ----------------------
// - Hall of Abyss
npc: npc\re\guild\invest_main_fr.txt

npc: npc\re\guild\invest_npc_fr.txt


npc: npc\re\guild3\agit_main_te_fr.txt

npc: npc\re\guild3\agit_start_te_fr.txt

npc: npc\re\guild3\te_aldecas1_fr.txt

npc: npc\re\guild3\te_aldecas2_fr.txt

npc: npc\re\guild3\te_aldecas3_fr.txt

npc: npc\re\guild3\te_aldecas4_fr.txt

npc: npc\re\guild3\te_aldecas5_fr.txt

npc: npc\re\guild3\te_prtcas01_fr.txt

npc: npc\re\guild3\te_prtcas02_fr.txt

npc: npc\re\guild3\te_prtcas03_fr.txt

npc: npc\re\guild3\te_prtcas04_fr.txt

npc: npc\re\guild3\te_prtcas05_fr.txt


// - Guild Mission
npc: npc\re\guild\mission_main_fr.txt

npc: npc\re\guild\mission_npc_fr.txt

