// --------------------------------------------------------------
// -                       Renewal Map Flags                    -
// --------------------------------------------------------------
npc: npc\re\mapflag\nopvp_fr.txt

npc: npc\re\mapflag\gvg_fr.txt

npc: npc\re\mapflag\hidemobhpbar_fr.txt

npc: npc\re\mapflag\nobranch_fr.txt

npc: npc\re\mapflag\nocostume_fr.txt

npc: npc\re\mapflag\noicewall_fr.txt

npc: npc\re\mapflag\nolockon_fr.txt

npc: npc\re\mapflag\nomemo_fr.txt

npc: npc\re\mapflag\nopenalty_fr.txt

npc: npc\re\mapflag\norenewalpenalty_fr.txt

npc: npc\re\mapflag\nosave_fr.txt

npc: npc\re\mapflag\noteleport_fr.txt

npc: npc\re\mapflag\nowarpto_fr.txt

//npc: npc/re/mapflag/partylock.txt
npc: npc\re\mapflag\privateairship_fr.txt

npc: npc\re\mapflag\night_fr.txt

npc: npc\re\mapflag\restricted_fr.txt

npc: npc\re\mapflag\town_fr.txt

npc: npc\re\mapflag\reset_fr.txt

npc: npc\re\mapflag\skill_duration_fr.txt

npc: npc\re\mapflag\nodynamicnpc_fr.txt

npc: npc\re\mapflag\specialpopup_fr.txt

