// --------------------------------------------------------------
// -                     Pre-Renewal Map Flags                  -
// --------------------------------------------------------------
npc: npc\pre-re\mapflag\hidemobhpbar_fr.txt

npc: npc\pre-re\mapflag\gvg_fr.txt

npc: npc\pre-re\mapflag\nosave_fr.txt

npc: npc\pre-re\mapflag\invincible_time_fr.txt

