// --------------------------------------------------------------
// -                  Pre-Renewal Monster Scripts               -
// --------------------------------------------------------------

npc: npc\pre-re\mobs\citycleaners_fr.txt


// -------------------------- Dungeons --------------------------
npc: npc\pre-re\mobs\dungeons\abbey_fr.txt

npc: npc\pre-re\mobs\dungeons\abyss_fr.txt

npc: npc\pre-re\mobs\dungeons\alde_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\ama_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\anthell_fr.txt

npc: npc\pre-re\mobs\dungeons\ayo_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\beach_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\c_tower_fr.txt

npc: npc\pre-re\mobs\dungeons\ein_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\gef_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\gefenia_fr.txt

npc: npc\pre-re\mobs\dungeons\glastheim_fr.txt

npc: npc\pre-re\mobs\dungeons\gld_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\gld_dunSE_fr.txt

npc: npc\pre-re\mobs\dungeons\gon_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\ice_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\in_sphinx_fr.txt

npc: npc\pre-re\mobs\dungeons\iz_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\juperos_fr.txt

npc: npc\pre-re\mobs\dungeons\kh_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\lhz_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\lou_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\mag_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\mjo_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\moc_pryd_fr.txt

npc: npc\pre-re\mobs\dungeons\mosk_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\nyd_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\odin_fr.txt

npc: npc\pre-re\mobs\dungeons\orcsdun_fr.txt

npc: npc\pre-re\mobs\dungeons\pay_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\prt_maze_fr.txt

npc: npc\pre-re\mobs\dungeons\prt_sew_fr.txt

npc: npc\pre-re\mobs\dungeons\ra_san_fr.txt

npc: npc\pre-re\mobs\dungeons\tha_t_fr.txt

npc: npc\pre-re\mobs\dungeons\thor_v_fr.txt

npc: npc\pre-re\mobs\dungeons\treasure_fr.txt

npc: npc\pre-re\mobs\dungeons\tur_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\um_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\xmas_dun_fr.txt

npc: npc\pre-re\mobs\dungeons\yggdrasil_fr.txt


// --------------------------- Fields ---------------------------
npc: npc\pre-re\mobs\fields\amatsu_fr.txt

npc: npc\pre-re\mobs\fields\ayothaya_fr.txt

npc: npc\pre-re\mobs\fields\comodo_fr.txt

npc: npc\pre-re\mobs\fields\einbroch_fr.txt

npc: npc\pre-re\mobs\fields\geffen_fr.txt

npc: npc\pre-re\mobs\fields\gonryun_fr.txt

npc: npc\pre-re\mobs\fields\hugel_fr.txt

npc: npc\pre-re\mobs\fields\lighthalzen_fr.txt

npc: npc\pre-re\mobs\fields\louyang_fr.txt

npc: npc\pre-re\mobs\fields\lutie_fr.txt

npc: npc\pre-re\mobs\fields\manuk_fr.txt

npc: npc\pre-re\mobs\fields\mjolnir_fr.txt

npc: npc\pre-re\mobs\fields\morocc_fr.txt

npc: npc\pre-re\mobs\fields\moscovia_fr.txt

npc: npc\pre-re\mobs\fields\niflheim_fr.txt

npc: npc\pre-re\mobs\fields\payon_fr.txt

npc: npc\pre-re\mobs\fields\prontera_fr.txt

npc: npc\pre-re\mobs\fields\rachel_fr.txt

npc: npc\pre-re\mobs\fields\splendide_fr.txt

npc: npc\pre-re\mobs\fields\umbala_fr.txt

npc: npc\pre-re\mobs\fields\veins_fr.txt

npc: npc\pre-re\mobs\fields\yuno_fr.txt

