// --------------------------------------------------------------
// -                      Monster  Scripts                      -
// --------------------------------------------------------------

npc: npc\mobs\jail_fr.txt

npc: npc\mobs\pvp_fr.txt

npc: npc\mobs\towns_fr.txt

