// --------------------------------------------------------------
// -                        Job  Scripts                        -
// --------------------------------------------------------------

// ------------------------- Job Quests -------------------------
// - 1-1 Expanded
npc: npc\jobs\1-1e\gunslinger_fr.txt

npc: npc\jobs\1-1e\ninja_fr.txt

npc: npc\jobs\1-1e\taekwon_fr.txt

// - 2-1
npc: npc\jobs\2-1\assassin_fr.txt

npc: npc\jobs\2-1\blacksmith_fr.txt

npc: npc\jobs\2-1\hunter_fr.txt

npc: npc\jobs\2-1\knight_fr.txt

npc: npc\jobs\2-1\priest_fr.txt

npc: npc\jobs\2-1\wizard_fr.txt

// - 2-1 Transcended
npc: npc\jobs\2-1a\AssassinCross_fr.txt

npc: npc\jobs\2-1a\HighPriest_fr.txt

npc: npc\jobs\2-1a\HighWizard_fr.txt

npc: npc\jobs\2-1a\LordKnight_fr.txt

npc: npc\jobs\2-1a\Sniper_fr.txt

npc: npc\jobs\2-1a\WhiteSmith_fr.txt

// - 2-1 Expanded
npc: npc\jobs\2-1e\StarGladiator_fr.txt

// - 2-2
npc: npc\jobs\2-2\alchemist_fr.txt

npc: npc\jobs\2-2\bard_fr.txt

npc: npc\jobs\2-2\crusader_fr.txt

npc: npc\jobs\2-2\dancer_fr.txt

npc: npc\jobs\2-2\monk_fr.txt

npc: npc\jobs\2-2\rogue_fr.txt

npc: npc\jobs\2-2\sage_fr.txt

// - 2-2 Transcended
npc: npc\jobs\2-2a\Champion_fr.txt

npc: npc\jobs\2-2a\Clown_fr.txt

npc: npc\jobs\2-2a\Creator_fr.txt

npc: npc\jobs\2-2a\Gypsy_fr.txt

npc: npc\jobs\2-2a\Paladin_fr.txt

npc: npc\jobs\2-2a\Professor_fr.txt

npc: npc\jobs\2-2a\Stalker_fr.txt

// - 2-2 Expanded
npc: npc\jobs\2-2e\SoulLinker_fr.txt

// - Novice
npc: npc\jobs\novice\supernovice_fr.txt

// - Transcended Quest (2-x -> High Novice)
npc: npc\jobs\valkyrie_fr.txt


// ------------------------ Skill Quests ------------------------
npc: npc\quests\skills\acolyte_skills_fr.txt

npc: npc\quests\skills\alchemist_skills_fr.txt

npc: npc\quests\skills\archer_skills_fr.txt

npc: npc\quests\skills\assassin_skills_fr.txt

npc: npc\quests\skills\bard_skills_fr.txt

npc: npc\quests\skills\blacksmith_skills_fr.txt

npc: npc\quests\skills\crusader_skills_fr.txt

npc: npc\quests\skills\dancer_skills_fr.txt

npc: npc\quests\skills\hunter_skills_fr.txt

npc: npc\quests\skills\knight_skills_fr.txt

npc: npc\quests\skills\mage_skills_fr.txt

npc: npc\quests\skills\merchant_skills_fr.txt

npc: npc\quests\skills\monk_skills_fr.txt

// npc: npc/quests/skills/novice_skills.txt
npc: npc\quests\skills\priest_skills_fr.txt

npc: npc\quests\skills\rogue_skills_fr.txt

npc: npc\quests\skills\sage_skills_fr.txt

npc: npc\quests\skills\swordman_skills_fr.txt

npc: npc\quests\skills\thief_skills_fr.txt

npc: npc\quests\skills\wizard_skills_fr.txt

