// --------------------------------------------------------------
// -                         Map  Flags                         -
// --------------------------------------------------------------
npc: npc\mapflag\nopvp_fr.txt

npc: npc\mapflag\gvg_fr.txt

npc: npc\mapflag\gvg_noparty_fr.txt

npc: npc\mapflag\hidemobhpbar_fr.txt

npc: npc\mapflag\jail_fr.txt

npc: npc\mapflag\nightmare_fr.txt

npc: npc\mapflag\nobranch_fr.txt

npc: npc\mapflag\noicewall_fr.txt

npc: npc\mapflag\nomemo_fr.txt

npc: npc\mapflag\nopenalty_fr.txt

npc: npc\mapflag\nosave_fr.txt

npc: npc\mapflag\noteleport_fr.txt

npc: npc\mapflag\noreturn_fr.txt

npc: npc\mapflag\noskill_fr.txt

npc: npc\mapflag\nowarp_fr.txt

npc: npc\mapflag\nowarpto_fr.txt

//npc: npc/mapflag/partylock.txt
npc: npc\mapflag\pvp_fr.txt

npc: npc\mapflag\pvp_noparty_fr.txt

npc: npc\mapflag\pvp_noguild_fr.txt

npc: npc\mapflag\night_fr.txt

npc: npc\mapflag\reset_fr.txt

npc: npc\mapflag\restricted_fr.txt

npc: npc\mapflag\battleground_fr.txt

npc: npc\mapflag\skill_damage_fr.txt

npc: npc\mapflag\town_fr.txt

npc: npc\mapflag\nocostume_fr.txt

npc: npc\mapflag\skill_duration_fr.txt

npc: npc\mapflag\nodynamicnpc_fr.txt

