// --------------------------------------------------------------
// -                        Warp Scripts                        -
// --------------------------------------------------------------

// --------------------------- Cities ---------------------------
npc: npc\warps\cities\alberta_fr.txt

npc: npc\warps\cities\aldebaran_fr.txt

npc: npc\warps\cities\amatsu_fr.txt

npc: npc\warps\cities\ayothaya_fr.txt

npc: npc\warps\cities\brasilis_fr.txt

npc: npc\warps\cities\comodo_fr.txt

npc: npc\warps\cities\einbech_fr.txt

npc: npc\warps\cities\einbroch_fr.txt

npc: npc\warps\cities\geffen_fr.txt

npc: npc\warps\cities\gonryun_fr.txt

npc: npc\warps\cities\hugel_fr.txt

npc: npc\warps\cities\lighthalzen_fr.txt

npc: npc\warps\cities\louyang_fr.txt

npc: npc\warps\cities\lutie_fr.txt

npc: npc\warps\cities\manuk_fr.txt

npc: npc\warps\cities\mid_camp_fr.txt

npc: npc\warps\cities\morroc_fr.txt

npc: npc\warps\cities\moscovia_fr.txt

npc: npc\warps\cities\nameless_fr.txt

npc: npc\warps\cities\niflheim_fr.txt

npc: npc\warps\cities\payon_fr.txt

npc: npc\warps\cities\prontera_fr.txt

npc: npc\warps\cities\splendide_fr.txt

npc: npc\warps\cities\umbala_fr.txt

npc: npc\warps\cities\veins_fr.txt

npc: npc\warps\cities\yuno_fr.txt


// -------------------------- Dungeons --------------------------
npc: npc\warps\dungeons\abbey_fr.txt

npc: npc\warps\dungeons\abyss_fr.txt

npc: npc\warps\dungeons\alde_dun_fr.txt

npc: npc\warps\dungeons\ama_dun_fr.txt

npc: npc\warps\dungeons\anthell_fr.txt

npc: npc\warps\dungeons\ayo_dun_fr.txt

npc: npc\warps\dungeons\beach_dun_fr.txt

npc: npc\warps\dungeons\bra_dun_fr.txt

npc: npc\warps\dungeons\c_tower_fr.txt

npc: npc\warps\dungeons\ein_dun_fr.txt

npc: npc\warps\dungeons\gef_dun_fr.txt

npc: npc\warps\dungeons\gon_dun_fr.txt

npc: npc\warps\dungeons\ice_dun_fr.txt

npc: npc\warps\dungeons\in_sphinx_fr.txt

npc: npc\warps\dungeons\iz_dun_fr.txt

npc: npc\warps\dungeons\juperos_fr.txt

npc: npc\warps\dungeons\kh_dun_fr.txt

npc: npc\warps\dungeons\lhz_dun_fr.txt

npc: npc\warps\dungeons\lou_dun_fr.txt

npc: npc\warps\dungeons\mag_dun_fr.txt

npc: npc\warps\dungeons\mjo_dun_fr.txt

npc: npc\warps\dungeons\moc_pryd_fr.txt

npc: npc\warps\dungeons\mosk_dun_fr.txt

npc: npc\warps\dungeons\odin_fr.txt

npc: npc\warps\dungeons\orcsdun_fr.txt

npc: npc\warps\dungeons\pay_dun_fr.txt

npc: npc\warps\dungeons\prt_maze_fr.txt

npc: npc\warps\dungeons\ra_san_fr.txt

npc: npc\warps\dungeons\tha_t_fr.txt

npc: npc\warps\dungeons\thor_v_fr.txt

npc: npc\warps\dungeons\treasure_fr.txt

npc: npc\warps\dungeons\tur_dun_fr.txt

npc: npc\warps\dungeons\um_dun_fr.txt

npc: npc\warps\dungeons\xmas_dun_fr.txt


// --------------------------- Fields ---------------------------
npc: npc\warps\fields\abyss_warper_fr.txt

npc: npc\warps\fields\amatsu_fild_fr.txt

npc: npc\warps\fields\bra_fild_fr.txt

npc: npc\warps\fields\ein_fild_fr.txt

npc: npc\warps\fields\gefenia_fr.txt

npc: npc\warps\fields\glastheim_fr.txt

npc: npc\warps\fields\jawaii_fr.txt

npc: npc\warps\fields\lhalzen_fild_fr.txt

npc: npc\warps\fields\lutie_fild_fr.txt

npc: npc\warps\fields\man_fild_fr.txt

npc: npc\warps\fields\mtmjolnir_fr.txt

npc: npc\warps\fields\spl_fild_fr.txt

npc: npc\warps\fields\umbala_fild_fr.txt


// --------------------------- Others ---------------------------
npc: npc\warps\other\airplane_fr.txt

npc: npc\warps\other\arena_fr.txt

npc: npc\warps\other\god_fr.txt

npc: npc\warps\other\jobquests_fr.txt

npc: npc\warps\other\kiel_fr.txt

npc: npc\warps\other\other_fr.txt

npc: npc\warps\guildcastles_fr.txt

npc: npc\warps\pvp_fr.txt

