// --------------------------------------------------------------
// -                        Test Scripts                        -
// --------------------------------------------------------------
// These scripts are meant for regression test purposes.

npc: npc\test\infinite_warp_fr.txt

npc: npc\test\OnInterInit_fr.txt

npc: npc\test\npc_test_checkweight_fr.txt

